// src/redux/constants/documentConstants.js

// Get all documents
export const GET_DOCUMENTS_REQUEST = 'GET_DOCUMENTS_REQUEST';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENTS_FAILURE = 'GET_DOCUMENTS_FAILURE';

// Get a single document
export const GET_DOCUMENT_REQUEST = 'GET_DOCUMENT_REQUEST';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';
export const GET_DOCUMENT_FAILURE = 'GET_DOCUMENT_FAILURE';

// Upload a document
export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAILURE = 'UPLOAD_DOCUMENT_FAILURE';

// Delete a document
export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';

// Update document status
export const UPDATE_DOCUMENT_STATUS_REQUEST = 'UPDATE_DOCUMENT_STATUS_REQUEST';
export const UPDATE_DOCUMENT_STATUS_SUCCESS = 'UPDATE_DOCUMENT_STATUS_SUCCESS';
export const UPDATE_DOCUMENT_STATUS_FAILURE = 'UPDATE_DOCUMENT_STATUS_FAILURE';

// Link documents to application
export const LINK_DOCUMENTS_REQUEST = 'LINK_DOCUMENTS_REQUEST';
export const LINK_DOCUMENTS_SUCCESS = 'LINK_DOCUMENTS_SUCCESS';
export const LINK_DOCUMENTS_FAILURE = 'LINK_DOCUMENTS_FAILURE';

// Check document expiry
export const CHECK_DOCUMENT_EXPIRY_REQUEST = 'CHECK_DOCUMENT_EXPIRY_REQUEST';
export const CHECK_DOCUMENT_EXPIRY_SUCCESS = 'CHECK_DOCUMENT_EXPIRY_SUCCESS';
export const CHECK_DOCUMENT_EXPIRY_FAILURE = 'CHECK_DOCUMENT_EXPIRY_FAILURE';

// Clear document errors
export const CLEAR_DOCUMENT_ERRORS = 'CLEAR_DOCUMENT_ERRORS';
