# .github/workflows/ci.yml
name: ThiQaX CI Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'mutawai-api/package-lock.json'
      
      - name: Install backend dependencies
        working-directory: mutawai-api
        run: npm ci
      
      - name: Lint backend code
        working-directory: mutawai-api
        run: npm run lint
      
      - name: Run backend tests
        working-directory: mutawai-api
        run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/thiqax-test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: test
          
      - name: Upload backend test coverage
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: mutawai-api/coverage
  
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'mutawai-client/package-lock.json'
      
      - name: Install frontend dependencies
        working-directory: mutawai-client
        run: npm ci
      
      - name: Lint frontend code
        working-directory: mutawai-client
        run: npm run lint
      
      - name: Run frontend tests
        working-directory: mutawai-client
        run: npm test -- --coverage
        
      - name: Upload frontend test coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: mutawai-client/coverage
          
  build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Build API
        working-directory: mutawai-api
        run: |
          npm ci
          npm run build --if-present
      
      - name: Build client
        working-directory: mutawai-client
        run: |
          npm ci
          npm run build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            mutawai-client/build
            mutawai-api/dist
