// src/store/types.js

// ===== Authentication Action Types =====
// Add these at the top of your existing types.js file
export const CHECK_AUTH_REQUEST = 'CHECK_AUTH_REQUEST';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

// ===== Your Existing Dashboard Action Types =====
// These are already in your types.js file
// Profile
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

// Applications
export const FETCH_APPLICATIONS_REQUEST = 'FETCH_APPLICATIONS_REQUEST';
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS';
export const FETCH_APPLICATIONS_FAILURE = 'FETCH_APPLICATIONS_FAILURE';

// Documents
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

// Agent Stats
export const FETCH_AGENT_STATS_REQUEST = 'FETCH_AGENT_STATS_REQUEST';
export const FETCH_AGENT_STATS_SUCCESS = 'FETCH_AGENT_STATS_SUCCESS';
export const FETCH_AGENT_STATS_FAILURE = 'FETCH_AGENT_STATS_FAILURE';

// Job Postings
export const FETCH_JOB_POSTINGS_REQUEST = 'FETCH_JOB_POSTINGS_REQUEST';
export const FETCH_JOB_POSTINGS_SUCCESS = 'FETCH_JOB_POSTINGS_SUCCESS';
export const FETCH_JOB_POSTINGS_FAILURE = 'FETCH_JOB_POSTINGS_FAILURE';

// Candidates
export const FETCH_CANDIDATES_REQUEST = 'FETCH_CANDIDATES_REQUEST';
export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILURE = 'FETCH_CANDIDATES_FAILURE';

// System Stats
export const FETCH_SYSTEM_STATS_REQUEST = 'FETCH_SYSTEM_STATS_REQUEST';
export const FETCH_SYSTEM_STATS_SUCCESS = 'FETCH_SYSTEM_STATS_SUCCESS';
export const FETCH_SYSTEM_STATS_FAILURE = 'FETCH_SYSTEM_STATS_FAILURE';

// Pending Verifications
export const FETCH_PENDING_VERIFICATIONS_REQUEST = 'FETCH_PENDING_VERIFICATIONS_REQUEST';
export const FETCH_PENDING_VERIFICATIONS_SUCCESS = 'FETCH_PENDING_VERIFICATIONS_SUCCESS';
export const FETCH_PENDING_VERIFICATIONS_FAILURE = 'FETCH_PENDING_VERIFICATIONS_FAILURE';

// Recent Users
export const FETCH_RECENT_USERS_REQUEST = 'FETCH_RECENT_USERS_REQUEST';
export const FETCH_RECENT_USERS_SUCCESS = 'FETCH_RECENT_USERS_SUCCESS';
export const FETCH_RECENT_USERS_FAILURE = 'FETCH_RECENT_USERS_FAILURE';
