// src/store/constants/documentConstants.js

export const DOCUMENT_UPLOAD_REQUEST = 'DOCUMENT_UPLOAD_REQUEST';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAIL = 'DOCUMENT_UPLOAD_FAIL';

export const DOCUMENT_LIST_REQUEST = 'DOCUMENT_LIST_REQUEST';
export const DOCUMENT_LIST_SUCCESS = 'DOCUMENT_LIST_SUCCESS';
export const DOCUMENT_LIST_FAIL = 'DOCUMENT_LIST_FAIL';

export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST';
export const DOCUMENT_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENT_DELETE_FAIL = 'DOCUMENT_DELETE_FAIL';

export const DOCUMENT_CLEAR_ERRORS = 'DOCUMENT_CLEAR_ERRORS';
